version: "3"

services:
  app:
    build: .
    ports:
      - 3005:3000
    environment:
      - MAX_WORKER=2
      - INTERNAL_API_HOST=http://localhost:3005
      - INTERNAL_FILE_HOST=http://localhost:3006
      - API_HOST=http://localhost:3005
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
